### ISSUE TITLE
Nodes without a URL still hyperlink the source field

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-frontend#162]
From https://het.io/search/?source=26663&target=14379

> ![image](https://user-images.githubusercontent.com/1117703/69872994-16c23c80-1285-11ea-9956-c0180933f475.png)

For the "source" field of the target node, the hyperlink for "Reactome via Pathway Commons" is empty:

```html
<div class="info_table_value small left"><div tabindex="0" class="dynamic_field " data-expanded="false"><a class="nowrap" href="">Reactome via Pathway Commons</a></div></div>
```

This is because [the API](https://search-api.het.io/v1/node/14379) does not return a URL: 

```json
{
    "id": 14379,
    "identifier": "PC7_6055",
    "identifier_type": "str",
    "name": "Orexin and neuropeptides FF and QRFP bind to their respective receptors",
    "properties": {
        "source": "Reactome via Pathway Commons",
        "license": "CC BY 4.0"
    },
    "metanode": "Pathway"
}
```
I'm thinking in these cases we should just not show any hyperlink rather than a blank one (which in my browser ends up going to the current address).

**Comment by vincerubinetti** [comment]
Sorry, didn't realize you had reported this several months before Casey mentioned it to me! This was closed with #163
